[package]
name = "voting_experts"
version = "0.1.0"
authors = ["Andrew Smith <andrewchristophersmith@gmail.com>"]

[dependencies]
radix_trie = { path = "/Users/acsmith/workspaces/rust/rust_radix_trie" }
